import type { Metadata } from "next";
import "./styles/globals.css";
import { open_sans, tinos } from "./fonts";
import { Navbar } from "./components/navbar";

export const metadata: Metadata = {
  title: "Omar Mohammad's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tinos.className} smooth-scroll`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
